### ISSUE TITLE
Can't override source files located in yml using comand line

### ISSUE THREAD

**Issue by rafrsr** [rafrsr/licenser#1]
Using the following config:

``` yml
finder:
  in:
    - src
parameters:
   author: Rafael SR <https://github.com/rafrsr>
   package: Licenser
   version: '@Rafrsr\Licenser\Licenser::VERSION'
```

Can't execute something like `bin/licenser MyClass.php --config=.licenser.yml`

This process all files defined in the configuration finder instead of only given file.

This type of execution is very common and helpful to process selected files or directories using the given configuration.
