### ISSUE TITLE
Multi-finder support

### ISSUE THREAD

**Issue by rafrsr** [rafrsr/licenser#4]
It could be very useful the posibility of configure muliple finders for each type of file or any other advanced usage

e.g.

``` yml
finder:
  php:
    in:
      - src
  javascript:
     in:
      - web/js/
     name: '*.js'
     notPath:
      - jquery
      - bootstrap
```
